name: Continuous Builder
on:
  workflow_dispatch:
  push:
    branches:
      - '**'
    paths-ignore:
      - 'metadata/**'
      - 'legal/**'
      - '**.md'
      - 'app/src/release/generated/baselineProfiles/**-prof.txt'
      - 'app/**.pro'
      - 'LICENSE'
      - '.github/workflows/release-builder.yml'
      - '.github/FUNDING.yml'
      - '.editorconfig'
      - '.idea/**'
  pull_request:

jobs:
  build:
    name: Continuous Builder
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo including backpack submodule
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '21'

      - name: Show backpack directory
        run: |
          cd backpack-apps
          ls
          cd ..

      - name: Build APK
        run: |
          chmod +x ./gradlew
          ./gradlew assembleRelease --stacktrace

      - name: List build output
        run: ls app/build/outputs/apk/release/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          path: app/build/outputs/apk/release/*.apk
          if-no-files-found: error
